syntax = "proto3";
package master_chunkserver;

service Heartbeat {
  rpc CollectStatus(CollectStatusRequest) returns (CollectStatusResponse);
  rpc AssignLease(AssignLeaseRequest) returns (AssignLeaseResponse);
}

message CollectStatusRequest {
  repeated uint64 available_chunks = 1;
}

message CollectStatusResponse {
  repeated uint64 deleted_chunks = 1;
  repeated uint64 leased_chunks = 2;
}

message AssignLeaseRequest {
  repeated uint64 handles = 1;
}

message AssignLeaseResponse {
  bool success = 1;
}
