syntax = "proto3";
package client_master;

service Fs {
  rpc Create(CreateRequest) returns (CreateResponse);
  rpc Write(WriteRequest) returns (WriteResponse);
}

message CreateRequest {
  string path = 1;
  bool is_directory = 2;
}

message CreateResponse {
  // TODO: Use more detail as failures occur
  enum Error {
    FILE_EXISTS = 0;
    INVALID_PATH = 1;
    OTHER = 2;
  }

  bool success = 1;
  optional Error error = 2;
}

message WriteRequest {
  string path = 1;
  uint64 offset = 2;
  uint64 length = 3;
}

message WriteResponse {
  // TODO: Use more detail as failures occur
  enum Error {
    FILE_DOES_NOT_EXIST = 0;
    INVALID_OFFSET = 1;
    INVALID_PATH = 2;
    PATH_IS_DIRECTORY = 3;
    OTHER = 4;
  }

  message ChunkLocation {
    string primary = 1;
    repeated string secondaries = 2;
  }

  bool success = 1;
  repeated ChunkLocation chunk_locations = 2;
  optional Error error = 3;
}

